[package]
name = "rusty_snn"
version = "0.1.0"
edition = "2021"
description = "A spiking neural network library written in Rust for research purposes."
license = "MIT OR Apache-2.0"
authors = ["Hugo Aguettaz <aguettaz@isi.ee.ethz.ch>"]

[dependencies]
rand = "0.8"
rand_distr = "0.4"
derivative = "2.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
itertools = "0.13"
tempfile = "3.14"
embed-doc-image = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }